services:
  postgres:
    image: postgres:17
    container_name: morpholoom-postgres
    environment:
      POSTGRES_DB: morpholoom
      POSTGRES_USER: morpholoom
      POSTGRES_PASSWORD: morpholoom123!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U morpholoom"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - morpholoom-network

  morpholoom:
    build:
      context: ./Morpholoom
      dockerfile: Dockerfile
    container_name: morpholoom-app
    working_dir: /app
    volumes:
      - ./storage:/app/src/storage
      - ./Morpholoom:/app/src
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "18080:8080"
      - "18888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/morpholoom
      SPRING_DATASOURCE_USERNAME: morpholoom
      SPRING_DATASOURCE_PASSWORD: morpholoom123!
    command: ["bash"]
    tty: true      
    # command: >
    #   sh -c "
    #     chmod +x ./mvnw && 
    #     ./mvnw clean install -DskipTests && 
    #     java -jar target/morpholoom-0.0.1-SNAPSHOT.jar
    #   "
    networks:
      - morpholoom-network

  # LivePortrait Python 애플리케이션
  liveportrait:
    build:
      context: ./LivePortrait
      dockerfile: Dockerfile
    container_name: liveportrait-app
    volumes:
      - ./LivePortrait:/app
      - ./LivePortrait/pretrained_weights:/app/pretrained_weights
      - ./storage/user/images:/app/assets/examples/source
      - ./storage/user/videos:/app/assets/examples/driving
      - ./storage/user/results:/app/animations

    ports:
      - "17860:7860"
    # command: ["python", "app.py", "--server_name", "0.0.0.0", "--server_port", "7860", "--flag_force_cpu"]
    command: ["bash"]
    tty: true
    gpus: all
    networks:
      - morpholoom-network

volumes:
  postgres_data:
  morpholoom_storage:
  liveportrait_weights:
  liveportrait_output:

networks:
  morpholoom-network:
    driver: bridge

