spring:
  application:
    name: Morpholoom
  datasource:
    driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://morpholoom-postgres:5432/morpholoom
    url: ${SPRING_DATASOURCE_URL}
    username: morpholoom
    password: ${DB_PASSWORD}
  thymeleaf:
    prefix: classpath:/static/
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: http://10.10.110.29:18081/realms/Morpholoom-realms
          issuer-uri: http://${HOST_IP}:${KEYCLOAK_PORT}/realms/Morpholoom-realms
  servlet:
    multipart:
      max-file-size: 100MB      # 단일 파일 최대 크기
      max-request-size: 100MB   # 전체 요청 최대 크기
  mail:
    host: smtp.gmail.com
    port: 587
    username: kdk7854@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
keycloak:
  realm: Morpholoom-realms
  # auth-server-url: http://10.10.110.29:18081
  auth-server-url: http://${HOST_IP}:${KEYCLOAK_PORT}
  resource: spring-boot-client
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET}
  # principal-attribute: preferred_username
# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.Morpholoom.domain

# Local file storage
storage:
  local:
    root-dir: ${STORAGE_ROOT_DIR:/app/src/storage}            # 서버 내 저장 경로
    public-base-url: /files        # 정적 제공 URL prefix

server:
  port: 8080
  servlet:
    context-path: /
    session.timeout: 60m

# Application settings
app:
  host-ip: ${HOST_IP:localhost}
  host-port: ${HOST_PORT:8080}
## Logging
logging.config: classpath:logback-spring-local.xml
logging.base.dir: logs

# HTTP retrieve
datacore:
  http:
    binding:
      response:
        log.yn: Y
      cause:
        msg:
          trace:
            key: x-detail-error-key
            value: BBBBB
          level: 3

http.pool:
  max.total: 200
  defaultMaxPerRoute: 100
  connection.timeout: 5000
  connection.request.timeout: 5000
  read.timeout: 10000
  validate.after.inactivity: 2000
